In [1]:
#Habilitar intellisense
%config IPCompleter.greedy = True

## Regresión logística

Es un algoritmo para obtener un clasificador binario. 

La regresión logística es bastante efectiva en situaciones en las que la relación entre la **probabilidad** de lograr una meta/objetivo (Y) está vinculada a los recursos necesarios (X) de manera no lineal donde una disminución/aumento de cierto recurso más allá de cierto umbral disminuye/aumenta drásticamente la probabilidad de lograr el objetivo.


<img src="logistica\01-lineal-vs-logistica_.png" style="width:600px"/>


<img src="logistica\02-regresion-logistica_.png" style="width:600px"/>


Los clasificadores binaros basados en regresión logística clasifican las observaciones de acuerdo a un umbral típicamente 0.5 (50%).

Hay dos técnicas comunmente empleadas para obtener los coeficientes de regresión:
- __[MLE](https://es.wikipedia.org/wiki/M%C3%A1xima_verosimilitud)__  
- __[Mínimos cuadrados](https://es.wikipedia.org/wiki/M%C3%ADnimos_cuadrados)__ (luego de convertir la relación establecida por la curva "S" a una relación lineal)


__[Scikit Learn - Regresión logística](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)__

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
df_entrenamiento = pd.read_csv(os.path.join("procesado", "train.csv"), index_col='PassengerId')

In [4]:
df_entrenamiento.head()

Survived   Age     Fare  FamilySize  IsMother  IsMale  Deck_A  \
PassengerId                                                                  
1                   0  22.0   7.2500           2         0       1     0.0   
2                   1  38.0  71.2833           2         0       0     0.0   
3                   1  26.0   7.9250           1         0       0     0.0   
4                   1  35.0  53.1000           2         0       0     0.0   
5                   0  35.0   8.0500           1         0       1     0.0   

             Deck_B  Deck_C  Deck_D  ...  Title_Sir  Fare_Bin_very_low  \
PassengerId                          ...                                 
1               0.0     0.0     0.0  ...        0.0                1.0   
2               0.0     1.0     0.0  ...        0.0                0.0   
3               0.0     0.0     0.0  ...        0.0                0.0   
4               0.0     1.0     0.0  ...        0.0                0.0   
5               0.0     0.0     0.0  ...        0.0                0.0   

             Fare_Bin_low  Fare_Bin_high  Fare_Bin_very_high  Embarked_C  \
PassengerId                                                                
1                     0.0            0.0                 0.0         0.0   
2                     0.0            0.0                 1.0         1.0   
3                     1.0            0.0                 0.0         0.0   
4                     0.0            0.0                 1.0         0.0   
5                     1.0            0.0                 0.0         0.0   

             Embarked_Q  Embarked_S  AgeState_Adult  AgeState_Child  
PassengerId                                                          
1                   0.0         1.0             1.0             0.0  
2                   0.0         0.0             1.0             0.0  
3                   0.0         1.0             1.0             0.0  
4                   0.0         1.0             1.0             0.0  
5                   0.0         1.0             1.0             0.0  

[5 rows x 33 columns]

In [5]:
df_entrenamiento.shape

(891, 33)

In [6]:
X = df_entrenamiento.loc[:,'Age':].to_numpy().astype('float')
y = df_entrenamiento['Survived'].ravel() 

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
# crear el clasificador
clasificador_reg_log = LogisticRegression(random_state=0, solver='liblinear')

In [10]:
# entrenar el clasificador
clasificador_reg_log.fit(X_train,y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [11]:
print('accuracy del clasificador - version 1 : {0:.2f}'.format(clasificador_reg_log.score(X_test, y_test)))

accuracy del clasificador - version 1 : 0.83


### El hiperparámetro 'penalty'
__[L1 Norms versus L2 Norms](https://www.kaggle.com/residentmario/l1-norms-versus-l2-norms)__

__[L1 and L2 Regularization Methods](https://towardsdatascience.com/l1-and-l2-regularization-methods-ce25e7fc831c)__

__[The difference between L1 and L2 regularization](https://explained.ai/regularization/L1vsL2.html)__

In [12]:
#evaluar el desempeño
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [13]:
# accuracy
print('accuracy del clasificador - version 1 : {0:.2f}'.format(accuracy_score(y_test, clasificador_reg_log.predict(X_test))))
# confusion matrix
print('matriz de confusión del clasificador - version 1: \n {0}'.format(confusion_matrix(y_test, clasificador_reg_log.predict(X_test))))
# precision 
print('precision del clasificador - version 1 : {0:.2f}'.format(precision_score(y_test, clasificador_reg_log.predict(X_test))))
# recall 
print('recall del clasificador - version 1 : {0:.2f}'.format(recall_score(y_test, clasificador_reg_log.predict(X_test))))
# f1
print('f1 del clasificador - version 1 : {0:.2f}'.format(f1_score(y_test, clasificador_reg_log.predict(X_test))))

accuracy del clasificador - version 1 : 0.83
matriz de confusión del clasificador - version 1: 
 [[95 15]
 [15 54]]
precision del clasificador - version 1 : 0.78
recall del clasificador - version 1 : 0.78
f1 del clasificador - version 1 : 0.78


In [14]:
# coeficientes del modelo
clasificador_reg_log.coef_

array([[-0.02840734,  0.00455631, -0.50017004,  0.61922838, -0.81414743,
         0.12823264, -0.17253859, -0.39355488,  0.52215008,  1.09939125,
         0.40346551, -0.18369316, -0.30021028,  0.96558544,  0.48281794,
        -0.3451608 ,  0.28258585,  1.21850069,  0.56334183, -1.44612507,
         1.07146232, -0.11345497, -0.47306807,  0.16297326,  0.24746349,
         0.27998252,  0.4128233 ,  0.49202884,  0.46214499,  0.14906873,
         0.37253571,  0.73070686]])

In [15]:
df_entrenamiento.loc[:,'Age':].columns

Index(['Age', 'Fare', 'FamilySize', 'IsMother', 'IsMale', 'Deck_A', 'Deck_B',
       'Deck_C', 'Deck_D', 'Deck_E', 'Deck_F', 'Deck_G', 'Deck_Z', 'Pclass_1',
       'Pclass_2', 'Pclass_3', 'Title_Lady', 'Title_Master', 'Title_Miss',
       'Title_Mr', 'Title_Mrs', 'Title_Officer', 'Title_Sir',
       'Fare_Bin_very_low', 'Fare_Bin_low', 'Fare_Bin_high',
       'Fare_Bin_very_high', 'Embarked_C', 'Embarked_Q', 'Embarked_S',
       'AgeState_Adult', 'AgeState_Child'],
      dtype='object')

In [16]:
list(zip(df_entrenamiento.loc[:,'Age':].columns, clasificador_reg_log.coef_[0]))

[('Age', -0.028407337097427984),
 ('Fare', 0.004556311933598024),
 ('FamilySize', -0.5001700443196179),
 ('IsMother', 0.6192283817250241),
 ('IsMale', -0.8141474271549188),
 ('Deck_A', 0.12823264145506164),
 ('Deck_B', -0.17253859381202133),
 ('Deck_C', -0.39355488439161285),
 ('Deck_D', 0.5221500810621986),
 ('Deck_E', 1.099391251831757),
 ('Deck_F', 0.403465513968498),
 ('Deck_G', -0.18369316305027036),
 ('Deck_Z', -0.3002102773455057),
 ('Pclass_1', 0.965585436279503),
 ('Pclass_2', 0.48281793789728056),
 ('Pclass_3', -0.3451608044586626),
 ('Title_Lady', 0.2825858490784899),
 ('Title_Master', 1.2185006862908279),
 ('Title_Miss', 0.5633418258150429),
 ('Title_Mr', -1.446125074480859),
 ('Title_Mrs', 1.0714623219795012),
 ('Title_Officer', -0.11345496801997268),
 ('Title_Sir', -0.4730680709449341),
 ('Fare_Bin_very_low', 0.16297326018403457),
 ('Fare_Bin_low', 0.2474634881001418),
 ('Fare_Bin_high', 0.2799825230984857),
 ('Fare_Bin_very_high', 0.4128232983353723),
 ('Embarked_C', 0.4

## Consideraciones

- En este ejemplo, los datos ya han sido preparados para poder emplearse como entrada para entrenar un modelo predictivo (clasificador binario). En la mayoría de los casos es muy difícil encontrar datos en tal estado y es necesario desarrollar una aplicación de datos para realizar la extracción y preparación de los datos

- El clasificador debe ser evaluado y cuando el desempeño sea el adecuado se despliega en producción (usualmente como un servicio REST que acepta nuevos casos y retorna la clasificación) 

- El proceso de entrenamiento y despliegue del clasificador también puede ser incluido en una aplicación de datos.

## Ejercicio clasificación
Crear un clasificador basado en el algoritmo de regresión logistica para predecir si el valor de la vivienda supera la media

entrada: housing.csv

Procedimiento:
- Cargar los datos los datos a un DataFrame y explorar brevemente
- Eliminar las observaciones que tengan algun dato faltante
- Eliminar las observaciones con el valor atípico (max) para la variable 'expected_house_value'
- Crear una nueva variable boolean 'above_median'
- Quitar 'expected_house_value'
- Aplicar los pasos train-test-split para poder entrenar y evaluar un clasificador basado en regresión logística

Cuáles los valores para accuracy, matriz de confusion, precision, recall y f1 del clasificador?

In [17]:
import pandas as pd
import numpy as np
import os

In [18]:
df_housing = pd.read_csv(os.path.join("housing.csv"))
df_housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  expected_house_value  \
0           322.0       126.0         8.3252              452600.0   
1          2401.0      1138.0         8.3014              358500.0   
2           496.0       177.0         7.2574              352100.0   
3           558.0       219.0         5.6431              341300.0   
4           565.0       259.0         3.8462              342200.0   
...           ...         ...            ...                   ...   
20635       845.0       330.0         1.5603               78100.0   
20636       356.0       114.0         2.5568               77100.0   
20637      1007.0       433.0         1.7000               92300.0   
20638       741.0       349.0         1.8672               84700.0   
20639      1387.0       530.0         2.3886               89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [19]:
df_housing.max()

longitude                  -114.31
latitude                     41.95
housing_median_age            52.0
total_rooms                39320.0
total_bedrooms              6445.0
population                 35682.0
households                  6082.0
median_income              15.0001
expected_house_value      500001.0
ocean_proximity         NEAR OCEAN
dtype: object

In [20]:
df_housing["expected_house_value"].describe()

count     20640.000000
mean     206855.816909
std      115395.615874
min       14999.000000
25%      119600.000000
50%      179700.000000
75%      264725.000000
max      500001.000000
Name: expected_house_value, dtype: float64

In [21]:
mean = 206855
std = 115395
df_housing = df_housing[df_housing.expected_house_value	 < mean+std]
df_housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
5        -122.25     37.85                52.0        919.0           213.0   
6        -122.25     37.84                52.0       2535.0           489.0   
7        -122.25     37.84                52.0       3104.0           687.0   
8        -122.26     37.84                42.0       2555.0           665.0   
9        -122.25     37.84                52.0       3549.0           707.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  expected_house_value  \
5           413.0       193.0         4.0368              269700.0   
6          1094.0       514.0         3.6591              299200.0   
7          1157.0       647.0         3.1200              241400.0   
8          1206.0       595.0         2.0804              226700.0   
9          1551.0       714.0         3.6912              261100.0   
...           ...         ...            ...                   ...   
20635       845.0       330.0         1.5603               78100.0   
20636       356.0       114.0         2.5568               77100.0   
20637      1007.0       433.0         1.7000               92300.0   
20638       741.0       349.0         1.8672               84700.0   
20639      1387.0       530.0         2.3886               89400.0   

      ocean_proximity  
5            NEAR BAY  
6            NEAR BAY  
7            NEAR BAY  
8            NEAR BAY  
9            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[17298 rows x 10 columns]

In [22]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

In [23]:
df_housing['above_median'] = np.where(df_housing['expected_house_value'] > 179700, True, False)
df_housing

C:\Users\nicol\AppData\Local\Temp\ipykernel_28192\3478557186.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_housing['above_median'] = np.where(df_housing['expected_house_value'] > 179700, True, False)


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
5        -122.25     37.85                52.0        919.0           213.0   
6        -122.25     37.84                52.0       2535.0           489.0   
7        -122.25     37.84                52.0       3104.0           687.0   
8        -122.26     37.84                42.0       2555.0           665.0   
9        -122.25     37.84                52.0       3549.0           707.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  expected_house_value  \
5           413.0       193.0         4.0368              269700.0   
6          1094.0       514.0         3.6591              299200.0   
7          1157.0       647.0         3.1200              241400.0   
8          1206.0       595.0         2.0804              226700.0   
9          1551.0       714.0         3.6912              261100.0   
...           ...         ...            ...                   ...   
20635       845.0       330.0         1.5603               78100.0   
20636       356.0       114.0         2.5568               77100.0   
20637      1007.0       433.0         1.7000               92300.0   
20638       741.0       349.0         1.8672               84700.0   
20639      1387.0       530.0         2.3886               89400.0   

      ocean_proximity  above_median  
5            NEAR BAY          True  
6            NEAR BAY          True  
7            NEAR BAY          True  
8            NEAR BAY          True  
9            NEAR BAY          True  
...               ...           ...  
20635          INLAND         False  
20636          INLAND         False  
20637          INLAND         False  
20638          INLAND         False  
20639          INLAND         False  

[17298 rows x 11 columns]

In [24]:
#df_housing.dropna(how="all")
y_col = 'expected_house_value'
bye_col = 'ocean_proximity'
df_housing = df_housing.drop(bye_col, axis=1)
df_housing = clean_dataset(df_housing)
df_housing = df_housing.reset_index()
y = df_housing[y_col]
df_housing = df_housing.drop(y_col, axis=1)
#X = df_housing.iloc[:,:-3].to_numpy().astype('float')
#y = df_housing['expected_house_value'].ravel() 
X = df_housing
X

index  longitude  latitude  housing_median_age  total_rooms  \
0          5    -122.25     37.85                52.0        919.0   
1          6    -122.25     37.84                52.0       2535.0   
2          7    -122.25     37.84                52.0       3104.0   
3          8    -122.26     37.84                42.0       2555.0   
4          9    -122.25     37.84                52.0       3549.0   
...      ...        ...       ...                 ...          ...   
17118  20635    -121.09     39.48                25.0       1665.0   
17119  20636    -121.21     39.49                18.0        697.0   
17120  20637    -121.22     39.43                17.0       2254.0   
17121  20638    -121.32     39.43                18.0       1860.0   
17122  20639    -121.24     39.37                16.0       2785.0   

       total_bedrooms  population  households  median_income  above_median  
0               213.0       413.0       193.0         4.0368           1.0  
1               489.0      1094.0       514.0         3.6591           1.0  
2               687.0      1157.0       647.0         3.1200           1.0  
3               665.0      1206.0       595.0         2.0804           1.0  
4               707.0      1551.0       714.0         3.6912           1.0  
...               ...         ...         ...            ...           ...  
17118           374.0       845.0       330.0         1.5603           0.0  
17119           150.0       356.0       114.0         2.5568           0.0  
17120           485.0      1007.0       433.0         1.7000           0.0  
17121           409.0       741.0       349.0         1.8672           0.0  
17122           616.0      1387.0       530.0         2.3886           0.0  

[17123 rows x 10 columns]

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(13698, 10) (13698,)
(3425, 10) (3425,)


In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
# crear el clasificador
clasificador_reg_log = LogisticRegression(random_state=0, solver='liblinear')

In [28]:
# entrenar el clasificador
clasificador_reg_log.fit(X_train,y_train)

C:\Users\nicol\anaconda3\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LogisticRegression(random_state=0, solver='liblinear')

In [29]:
#evaluar el desempeño
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [30]:
# accuracy
print('accuracy del clasificador - version 1 : {0:.2f}'.format(accuracy_score(y_test, clasificador_reg_log.predict(X_test))))
# confusion matrix
print('matriz de confusión del clasificador - version 1: \n {0}'.format(confusion_matrix(y_test, clasificador_reg_log.predict(X_test))))
# precision 
print('precision del clasificador - version 1 : {0:.2f}'.format(precision_score(y_test, clasificador_reg_log.predict(X_test))))
# recall 
print('recall del clasificador - version 1 : {0:.2f}'.format(recall_score(y_test, clasificador_reg_log.predict(X_test))))
# f1
print('f1 del clasificador - version 1 : {0:.2f}'.format(f1_score(y_test, clasificador_reg_log.predict(X_test))))

accuracy del clasificador - version 1 : 0.01
matriz de confusión del clasificador - version 1: 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [ ]:
list(zip(df_housing.columns.drop(y_col), clasificador_reg_log.coef_[0]))